slithers_controller:
  ros__parameters:
    simulator: gazebo
    joint_state_topic: /joint_states
    command_topic: /joint_trajectory_controller/joint_trajectory
    joint_names:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    control_rate_hz: 100.0
    command_duration_s: 0.02
